server:
  port: 28082

spring:
  application:
    name: PRODUCT-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sampledb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:http://localhost:28085